apiVersion: platform.connectedcare.io/v1alpha1
kind: App
metadata:
  name: payment
spec:
  name: payment
  namespace: platform-demo
  component: api
  partOf: astroshop
  version: 2.1.3-payment
  image: ghcr.io/open-telemetry/demo:2.1.3-payment
  port: 8080
  replicas: 1
  dependencies:
    database:
      enabled: true
      databaseClusterName: payment-db
    cache:
      enabled: true
      cacheClusterName: cart-cache
  config:
    data: {}
  runtime:
    imagePullSecrets: []
    imagePullPolicy: IfNotPresent
    serviceAccountName: payment
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    podAnnotations: {}
    nodeSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  service:
    type: ClusterIP
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  route:
    enabled: false
    gatewayName: ""
    gatewayNamespace: ""
    hostnames: []
    pathPrefix: /
  externalSecret:
    enabled: false
    secretStoreRefName: ""
    secretStoreKind: ClusterSecretStore
    targetSecretName: ""
    refreshInterval: 1h
    extractKey: ""
  certificate:
    enabled: false
    issuerName: ""
    issuerKind: ClusterIssuer
    secretName: ""
    dnsNames: []
