apiVersion: platform.connectecare.io/v1alpha1
kind: App
metadata:
  name: currency
spec:
  name: currency
  namespace: platform-kro-currency
  component: currency
  partOf: opentelemetry-demo
  version: 2.1.3
  image: ghcr.io/open-telemetry/demo:2.1.3-currency
  port: 8080
  replicas: 1
  dependencies:
    database:
      enabled: false
      databaseClusterName: ""
    cache:
      enabled: false
      cacheClusterName: ""
  config:
    data:
      OTEL_SERVICE_NAME: currency
      OTEL_COLLECTOR_NAME: otel-collector
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
      CURRENCY_PORT: "8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      VERSION: "2.1.3"
      OTEL_RESOURCE_ATTRIBUTES: service.name=currency,service.namespace=platform-kro-currency,service.version=2.1.3
  runtime:
    imagePullSecrets: []
    imagePullPolicy: IfNotPresent
    serviceAccountName: currency
    deploymentAnnotations: {}
    podAnnotations: {}
    nodeSelector: {}
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 250m
        memory: 20Mi
  service:
    type: ClusterIP
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  route:
    enabled: false
    gatewayName: ""
    gatewayNamespace: ""
    hostnames: []
    pathPrefix: /
  externalSecret:
    enabled: false
    secretStoreRefName: ""
    secretStoreKind: ClusterSecretStore
    targetSecretName: ""
    refreshInterval: 1h
    extractKey: ""
  certificate:
    enabled: false
    issuerName: ""
    issuerKind: ClusterIssuer
    secretName: ""
    dnsNames: []
