apiVersion: platform.connectedcare.io/v1alpha1
kind: App
metadata:
  name: restricted-nginx
  namespace: platform-kro-restricted
spec:
  name: restricted-nginx
  namespace: platform-kro-restricted
  component: web
  partOf: platform-kro
  version: stable
  image: nginxinc/nginx-unprivileged:stable-alpine-slim
  port: 8080
  replicas: 1
  config:
    revision: restricted-1
    envFromConfigMaps:
      - name: restricted-nginx-extra
    envFromSecrets:
      - name: restricted-nginx-secret
  runtime:
    readinessProbe:
      enabled: true
      path: /
      initialDelaySeconds: 1
      periodSeconds: 5
    livenessProbe:
      enabled: true
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10
    restrictedSecurity:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
  service:
    type: ClusterIP
  serviceMonitor:
    enabled: true
    path: /
    interval: 30s
    scrapeTimeout: 10s
  disruptionBudget:
    enabled: true
    maxUnavailableCount: 1
